### VARS
@baseUrl=http://localhost:3000
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyX0U4eTd6T3RBWXNleWVoOTZmdThfOCIsImVtYWlsIjoiYWRtaW5AYWNtZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzY4NTg0MjUsImV4cCI6MTc3Njk0NDgyNX0.WvO9C5rbBD704i3VoyBKb330opSr5TGNk3N3oUKDIeA
@userId=past_user_id_here

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@acme.com",
    "password": "Admin@123"
}

### list users
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}

### Get profile
GET {{baseUrl}}/me
Authorization: Bearer {{accessToken}}

### get user
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{accessToken}}

### create user
POST {{baseUrl}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@acme.com",
    "password": "A12345@321c",
    "dateOfBirth": "1992-11-03"
}

### update user
PATCH {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "email": "john.doe@acme-nevada.com"
}

### delete user
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{accessToken}}