### list users
GET http://localhost:3000/users

### get user
GET http://localhost:3000/users/dev_XvT4alGDQjpK3F9RsZmmh

### create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@acme.com",
    "password": "A12345@321c",
    "dateOfBirth": "1990-01-01"
}

### update user
PATCH http://localhost:3000/users/dev_XvT4alGDQjpK3F9RsZmmh
Content-Type: application/json

{
    "email": "john.doe@acme-nevada.com"
}

### delete user
DELETE http://localhost:3000/users/dev_XvT4alGDQjpK3F9RsZmmh