### VARS
@baseUrl=http://localhost:3000
@accessToken=past_access_token_here
@userId=past_user_id_here

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "john.doe@acme.com",
    "password": "A12345@321c"
}

### list users
GET http://localhost:3000/users

### get user
GET http://localhost:3000/users/{{userId}}

### create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@acme.com",
    "password": "A12345@321c",
    "dateOfBirth": "1990-01-01"
}

### update user
PATCH http://localhost:3000/users/{{userId}}
Content-Type: application/json

{
    "email": "john.doe@acme-nevada.com"
}

### delete user
DELETE http://localhost:3000/users/{{userId}}