### VARS
@baseUrl=http://localhost:3000
@accessToken=past_access_token_here
@taskId=past_task_id_here

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "john.doe@acme.com",
    "password": "A12345@321c"
}

### Create task
POST {{baseUrl}}/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Estudy NestJS",
    "description": "Complete auth module",
    "dueDate": "2026-04-20"
}

### List tasks
GET {{baseUrl}}/tasks
Authorization: Bearer {{accessToken}}

### Find especific task
GET {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}

### Update task
PATCH {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "completed": false
}

### Toogle complete
PATCH {{baseUrl}}/tasks/{{taskId}}/toggle
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Delete task
DELETE {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}